name: GitHub Actions

on:
 - push
 - pull_request

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Download Dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore --nologo

      - name: Test
        run: dotnet test -c Release --no-build --nologo
